services:
  postgres:
    container_name: banco_postgres
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=exemplo_node
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: banco_cache_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

volumes:
  postgres_data:
  redis_data: